### ISSUE TITLE
Yahoo OAuth unable to complete

### ISSUE THREAD

**Issue by doggy8088** [RockstarLabs/OwinOAuthProviders#10]
I was tried to setup a Yahoo OAuth using OwinOAuthProviders.  I was always get the following error during external login process.  Every time I press the "Yahoo" button to login are facing a HttpRequestException in the /Account/ExternalLogin page,  Here is the error message and screenshot.

`Response status code does not indicate success: 401 (Authorization Required).`

![image](https://cloud.githubusercontent.com/assets/88981/2831803/a5c39390-cfbd-11e3-9f8b-91aeba78820f.png)

I'm sure that my Yahoo apps been configured correctly.  My testing domain is also verified.

**Comment by jerriep** [comment]
@doggy8088 Please follow this step by step guide and let me know whether it works for you:
http://www.beabigrockstar.com/guides/aspnet-mvc-yahoo-login/

**Comment by doggy8088** [comment]
@jerriep That's weird.  It works now.  I was do the same steps yesterday.  :confused: 

Thanks anyway! :smile:

**Comment by jerriep** [comment]
@doggy8088 Yeah, I was also getting very weird intermittent errors with Yahoo when I was writing up that guide

**Comment by doggy8088** [comment]
@jerriep Thanks a lot. :+1:

**Comment by irquintanas** [comment]
Hi @jerriep,

I am having an issue with Yahoo authorization as well. Please let me explain the details:
-I started a new project from scratch directly cloning this Repo
-I use VS2013 Express for Web
-I can succesfully log through Linkedin, Google, Facebook, Microsoft and Twitter.
-But with Yahoo, after following several times the steps as mentioned in your post above, the application keeps behaving unexpectedly: when trying to log through Yahoo, it forwards correctly to Yahoo and they request the credentials succesfully and also returns back to the web application, but the problem is that the logininfo variable in procedure ExternalLoginCallback remains always to null even after the GetExternalLoginInfoAsync(), so it returns unlogged directly to /Login page, as the code states, not throwing any exception at all.
-I have checked the logininfo variable in al of the resting cases mentioned above, and it is set to the corresponding values after the GetExternalLoginInfoAsync().

Please let me know any idea you could have.

Thanks in advance and congratulations for your great project.

Iago

**Comment by jerriep** [comment]
@irquintanas I wish I could give you a proper answer. I keep getting intermittent errors with the Yahoo provider. Sometimes something will not work, and a few hours later the same application will work without having made any changes. 

I do not think the errors are on our side as I have seen other people report similar issues connecting to the Yahoo APIs through other frameworks...

For now all I can suggest is that you follow the instructions in this guide:
http://www.beabigrockstar.com/guides/aspnet-mvc-yahoo-login/

**Comment by irquintanas** [comment]
Thanks @jerriep, I had already followed your great set of posts regarding external authentication in Be a Big Rockstar (by the way, for you to know, you have a little mistake in the Yahoo post in the last paragraph: you mention GitHub instead. Image attached)
![beabigrockstar](https://cloud.githubusercontent.com/assets/5934240/2996470/831deacc-dcef-11e3-85e9-6fe691efb940.png)

Yes, I detected anormal and random behaviour using the Yahoo API as well, so who knows...

OK, thanks anyway.

**Comment by jerriep** [comment]
Thank you for pointing that out, it has been fixed
