### ISSUE TITLE
Possible problem with UseYahooAuthentication

### ISSUE THREAD

**Issue by julesongithub** [RockstarLabs/OwinOAuthProviders#16]
Hi,

I've followed all the steps in the blog post here to set up using the Yahoo login:
http://www.beabigrockstar.com/guides/aspnet-mvc-yahoo-login/

I'm using a proper external domain and I've also successfully verified the domain by uploading the Yahoo provided html page to my site.

When I click login, I'm taken to the landing page where I'm asked to click the button to agree to the login. After this, it fails. I've examined the network in chrome and this is what I see:

http://mediajuicer.com/registerexternallogin?providerName=Yahoo&returnUrl=&error=access_denied

Here's the full list of requests (as far as I can see in chrome):

After clicking sign-in on my site:
1. https://api.login.yahoo.com/oauth/v2/request_auth?oauth_token=bm6vgxg
2. https://api.login.yahoo.com/oauth/v2/request_auth?oauth_token=bm6vgxg&crumb=.Uw7zuUdbBL

After clicking I Agree at Yahoo:
1. https://api.login.yahoo.com/oauth/v2/request_auth
2. http://mediajuicer.com/signin-yahoo?oauth_token=bm6vgxg&oauth_verifier=ekmryb
3. http://mediajuicer.com/registerexternallogin?providerName=Yahoo&returnUrl=&error=access_denied

Any ideas what's going on?

Cheers,
Jules

**Comment by jerriep** [comment]
@julesongithub Unfortunately Yahoo is giving me a headache. The login process will give intermittent issues which does not seem to be consistently reproducible. Various people reported that they experienced issues, and sometimes just waiting a few hours and trying again later will make the problem disappear.

I also do not have the time right now to try and debug this... If you have the time and willingness to debug the code and see if you can track down any issues, it would be highly appreciated ;)

**Comment by julesongithub** [comment]
Unfortunately I don't have time at the moment either. If I get some time at the weekend, I'll certainly give it a crack and see if I can see what's going on.

**Comment by dotus-git** [comment]
FWIW: Getting the same issues following the same guidelines.

**Comment by awr** [comment]
I'm running into the same thing. After a little debugging, it appears that YahooAuthenticatedContext.GetEmail expects an "email" attribute on the json that comes back from http://social.yahooapis.com/v1/user/{guid}/profile/usercard -- for me, this is null, which ultimately cascades into the return of error=access_denied.

Looking at the docs from https://developer.yahoo.com/social/rest_api_guide/usercard-resource.html, I'm not sure where the email property would come from -- perhaps it's changed on the yahoo side?

**Comment by awr** [comment]
So I take back my comment about which endpoint you're hitting -- got that from the comments rather than the live code (my bad).

The code actually runs a query as follows:
https://query.yahooapis.com/v1/yql?q=select%20%2A%20from%20social.profile%20where%20guid%3Dme&format=json

Running this through Fiddler (with the appropriate headers) does _not_ give the emails property for profile. However, running a very similar query from https://developer.yahoo.com/yql/console does. The query generated for me is https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20social.profile%20where%20guid%3Dme&format=json&callback=

The key differences appear to be:
1) different creds
2) the inclusion of callback= (returns a 401 if I add this to the fiddler query)
3) v1/public/yql vs v1/yql (returns a 400 if I try to use this endpoint from fiddler)
This last one looks the most promising. It includes in the response:
description=Authentication Error.  The table social.profile requires a higher security level than is provided, you provided ANY but at least APP is expected

**Comment by awr** [comment]
Ultimately for me, this came down to adding more rights to my Yahoo app.

The reason I had put in the incorrect credentials in the first place was because the guide at http://www.beabigrockstar.com/guides/aspnet-mvc-yahoo-login/, which indicates that we need to have readonly access to contacts. I found that what we really need is Read/Write Public and Private to Social Directory (Profiles).

That being said, it might be nice if the code gave a more helpful error response in this scenario -- to help other developers troubleshoot.

**Comment by jerriep** [comment]
@awr Thank you very much for the detailed writeup. I will make the code more resilient to insufficient permissions and also update the guide accordingly.

**Comment by beribener** [comment]
Same problems by me. Could not solve by granting the yahoo app more creds as @awr has suggested. Any help would be greatly appreciated.

**Comment by pixel-shift** [comment]
So it's failing for us too, with 'access_denied'.

We've drilled in to it for quite a while and pinned it down to the 'ObtainUserProfile' call in the YahooAuthenticationHandler class. After the GET request is formed, signed etc and submitted, the response from yahoo is:

&lt;yahoo:description&gt;Please provide valid credentials. OAuth oauth_problem=&quot;OST_OAUTH_SIGNATURE_INVALID_ERROR&quot;, realm=&quot;yahooapis.com&quot;&lt;/yahoo:description&gt;&lt;yahoo:detail&gt;Please provide valid credentials. OAuth oauth_problem=&quot;OST_OAUTH_SIGNATURE_INVALID_ERROR&quot;, realm=&quot;yahooapis.com&quot;&gt;&lt;/yahoo:detail&gt;

There doesn't seem to be anything obviously wrong with the signature generation.

We also came across this post: 
https://developer.yahoo.com/forum/OAuth-General-Discussion-YDN-SDKs/OST-OAUTH-SIGNATURE-INVALID-ERROR/1404240150116-1325679c-ee21-4385-90cf-4ccee8334d85/1404240150116

where it seems that his/her code has also broken suddenly without making any changes.

**Comment by ghost** [comment]
Hello, I am new to github and to Owin middlewares. I am using this project of yours to understand how authentication middlewares are written.

In Line 47 of https://github.com/owin-middleware/OwinOAuthProviders/blob/master/Owin.Security.Providers/Yahoo/Provider/YahooAuthenticatedContext.cs the comment says LinkedIn user. Could you please clarify if this is a typo or I am missing something?

Update: Thank you. I am quite new to this. That's why I got confused. Thanks for the clarification.

**Comment by jerriep** [comment]
@payojbaral I copied and pasted a lot of the code. Just missed changing the comment. Will fix it

**Comment by jerriep** [comment]
I have time to look at this today guys. Hopefully I can get a fix for this

**Comment by jerriep** [comment]
Ok, this issue is now fixed in version 1.5.1. The latest package is available on Nuget.

Please take note of how to use the Yahoo provider at http://www.beabigrockstar.com/guides/aspnet-mvc-yahoo-login/. As stated in the guide you will need to use a tool like ngrok for testing against localhost
