### ISSUE TITLE
Rename project, assembly and nuget package to Microsoft.Owin.SecurityEx

### ISSUE THREAD

**Issue by damianh** [RockstarLabs/OwinOAuthProviders#8]
This project depends on Microsoft.Owin.Security and the owin spec doesn't (yet) specify anything regarding security or identity. Calling it Owin.Security may cause confusion for users.

I suggest renaming this repository, the project, the resulting assembly and the nuget package to Microsoft.Owin.SecurityEx. I also suggest changing the project's namespace to Microsoft.Owin.Security to aid discoverability for users.

**Comment by leastprivilege** [comment]
I don't think that makes sense. The library is not from Microsoft. And Ex is bit 90ish ;) Rename to something like OwinContrib or whatever...

**Comment by damianh** [comment]
Owin Contrib is way too generic imho...

**Comment by leastprivilege** [comment]
OwinContrib.Security.LinkedIn e.g. ?

**Comment by jerriep** [comment]
Sorry guys but I believe changing the namespaces and Nuget package name at this stage is going to cause more confusion than anything else.  Lot of people already using the package are going to get compiler errors because namespaces doesn't exist anymore.  

Also I have written a number of blog posts to get the word out about the package (referencing it by name) and if it changes now people searching for it based on that package name won't be able to find it anymore.

I am with you though on the discoverability issue - though I do not think the changing the name is going to make it any better.  Searching for anything on Nuget brings back massive amounts of irrelevant search results.

**Comment by damianh** [comment]
There are ways to mitigate all that. None the less, I strongly suspect it's
name wrt dependencies is going to cause problems with the owin governance
group.

**Comment by jerriep** [comment]
I understand your concern and will see if I can raise the issue with the relevant people. If they can give clarity as to whether it will be an issue and suggest an appropriate alternative name then I will change it.

**Comment by damianh** [comment]
Thanks @jerriep , that's reasonable.
